[api]
port = ":4000"
name = "Bolierplate - API"
generateDB = true

[database]
host = "localhost"
port = "5432"
user = "postgres"
pass = "Postgress2022!"
name = "postgres"


[recaptcha]
secret = ""
sitekey = ""

[sengrid]
apiKey = ""


